# Set permissions
xhost +SI:localuser:$USER

# Set fallback cursor
xsetroot -cursor_name left_ptr

# Set keyboard repeat rate
xset r rate 200 60

export VISUAL=emacsclient
export EDITOR="$VISUAL"

# Load resources
xrdb -load ~/.config/X11/Xresources

exec emacs
